app/blueprints/multilingual/routes.py
import datetime
import ipaddress
import json
from flask import (jsonify, render_template, Blueprint, g, redirect, send_file, send_from_directory, session,
                   request, current_app, abort, flash, url_for)
from app.controllers.uploadFunctions import refreshFirmware, restartService
from app.db.sqlProcess import *
import sqlite3
import app.controllers.statuspage as statuspage
from app.controllers.ssocket import *
from app.controllers import validator
from app.controllers import *
import app.controllers.syslogController as syslogFunc
import app.controllers.logView as journalctl
import app.controllers.iptables as iptables
import app.controllers.bridge as bridge

from flask_babel import _
from app import app
import os


con = sqlite3.connect("./app/db/login.db", check_same_thread=False)
cursor = con.cursor()

UPLOAD_FOLDER = '/root'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'


multilingual = Blueprint('multilingual', __name__,
                         template_folder='templates', url_prefix='/<lang_code>')


@multilingual.url_defaults
def add_language_code(endpoint, values):
    if 'lang_code' in values or not g.lang_code:
        return
    if app.url_map.is_endpoint_expecting(endpoint, 'lang_code'):
        values['lang_code'] = g.lang_code


@multilingual.url_value_preprocessor
def pull_lang_code(endpoint, values):
    if values is None:
        values = {}
    g.lang_code = values.pop('lang_code', None)


@multilingual.before_request
def before_request():
    if g.lang_code not in current_app.config['LANGUAGES']:
        adapter = app.url_map.bind('')
        try:
            endpoint, args = adapter.match(
                '/en' + request.full_path.rstrip('/ ?'))
            return redirect(url_for(endpoint, **args), 301)
        except:
            print("Hata!!")

    dfl = request.url_rule.defaults
    if 'lang_code' in dfl:
        if dfl['lang_code'] != request.full_path.split('/')[1]:
            abort(404)

# Giriş route u ilk açılışta login e yönlendirir.


@app.route('/')
def route():
    os.system("mkdir /root/conf")
    return redirect('/en')

# İlk webserver açılışında Default username pass değiştirme sayfası route
@multilingual.route("/updateDefaultUser", defaults={"lang_code": "en"}, methods=['GET', "POST"])
@multilingual.route("/userGuncelle", defaults={"lang_code": "tr"}, methods=['GET', "POST"])
def updateDefaultUser():
    if request.method == 'GET':
        try:
            session['defaultUser']
        except:
            return redirect('/')
        return render_template("multilingual/changeDefaultPass.html", EditUserInfo=fetchInfo("id", 0, "USERS"))
    if request.method == 'POST':
        if validator.usernameValid(request.form['newUsername']):
            if validator.password_check(request.form['newUserPassword']):
                if validator.emailValid(request.form['newUserMail']):
                    message = str(validator.emailValid(
                        request.form["newUserMail"]))
                    flash(message)
                    return redirect(url_for("multilingual.updateDefaultUser"))
                else:
                    updateUser(request.form['newUsername'], request.form['newUserPassword'],
                               request.form['newUserMail'], "Administrator", "0", "-")
            else:
                flash(
                    'Password must be 8-16 characters long and contain one uppercase and one lowercase character.')
                return redirect(url_for("multilingual.updateDefaultUser"))
        else:
            flash('Invalid username!')
            return redirect(url_for("multilingual.updateDefaultUser"))
        return redirect('/')


@multilingual.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if 'username' in session:
            return render_template('multilingual/index.html', userInfo=session['username'], auth=getAuth(session['username']), uptime=statuspage.getTimeUp(), time=statuspage.getTime(), ramUsage=statuspage.ramUsage(), netstatus=statuspage.interfaceControl(), dataType1=soc.dataType2)
            #return render_template('multilingual/index.html', userInfo=session['username'], auth=getAuth(session['username']), uptime="statuspage.getTimeUp()", time="statuspage.getTime()", ramUsage="statuspage.ramUsage()", netstatus="statuspage.interfaceControl()", dataType1="asd")
        else:
            return render_template('multilingual/login.html')
    if request.method == 'POST':
        cursor.execute('SELECT username,password,auth FROM USERS where username =? and password=?',
                       (request.form['username'], request.form['password']))
        global user
        user = cursor.fetchone()
        try:
            print(user[0])
            print(getAuth(user[0])[0])
        except:
            flash('Username or Password is incorrect.')
            return redirect('/en')
        # Default password change page route
        if request.form["username"] == "admin" and request.form["password"] == "admin":
            session['defaultUser'] = 1
            return redirect(url_for('multilingual.updateDefaultUser'))
        if (getAuth(user[0])[0] == "Technician" or getAuth(user[0])[0] == "Operator") and getIp(user[0])[0] == request.remote_addr:
            session['username'] = user[0]
            return redirect('index')
        elif getAuth(user[0])[0] == "Administrator":
            session['username'] = user[0]
            print(session)
            return render_template('multilingual/index.html', userInfo=session['username'], netstatus=statuspage.interfaceControl(), auth=getAuth(session['username']), uptime=statuspage.getTimeUp(), time=statuspage.getTime(), ramUsage=statuspage.ramUsage(), dataType1=soc.dataType2)
        elif getIp(user[0])[0] != request.remote_addr:
            print(request.remote_addr)
            flash('IP not authorized to access!')
            return redirect('/en')
        else:
            flash('Username or Password is incorrect.')
            return redirect('/en')

@multilingual.route('/index')
def index():
    if request.method == 'GET':
        try:
            session['username']
        except:
            return redirect('/')
        return render_template('multilingual/index.html', userInfo=session['username'], auth=getAuth(session['username']), uptime=statuspage.getTimeUp(), time=statuspage.getTime(), ramUsage=statuspage.ramUsage(), netstatus=statuspage.interfaceControl(), dataType1=soc.dataType1)

@multilingual.route('/logout', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST':
        session.clear()
        print("session temizlendi")
        return redirect('/')

@multilingual.route('/uploadProject', defaults={'lang_code': 'en'}, methods=['GET', 'POST'])
@multilingual.route('/projeYukle', defaults={'lang_code': 'tr'}, methods=['GET', 'POST'])
def uploadProject():
    if request.method == 'GET':
        try:
            session['username']
        except:
            return redirect('/')
        return render_template('multilingual/uploadProject.html', userInfo=session['username'], auth=getAuth(session['username']))
    if request.method == 'POST':
        uploaded_file = request.files['project']
        if uploaded_file.filename != " ":
            uploaded_file.filename = "project"
            uploaded_file.save(os.path.join(
                app.config['UPLOAD_FOLDER'], uploaded_file.filename))
            print("Project File uploaded!!")
            restartService()
        return redirect(url_for('multilingual.uploadProject'))


@multilingual.route('/firmwareYukle', defaults={'lang_code': 'tr'}, methods=['GET', 'POST'])
@multilingual.route('/uploadFirmware', defaults={'lang_code': 'en'}, methods=['GET', 'POST'])
def uploadFirmware():
    if request.method == 'GET':
        try:
            session['username']
        except:
            return redirect('/')
        return render_template('multilingual/uploadFirmware.html', userInfo=session['username'], auth=getAuth(session['username']))
    if request.method == 'POST':
        uploaded_file = request.files['firmware']
        if uploaded_file.filename != '':
            uploaded_file.filename = "core.mx3"
            uploaded_file.save(os.path.join(
                app.config['UPLOAD_FOLDER'], uploaded_file.filename))
            print("File uploaded!!")
            refreshFirmware(uploaded_file.filename)
            print("Firmware refreshing...")
        return redirect(url_for('multilingual.uploadFirmware'))


@multilingual.route('/sslGuncelle', defaults={'lang_code': 'tr'}, methods=['GET', 'POST'])
@multilingual.route('/sslUpdatePage', defaults={'lang_code': 'en'}, methods=['GET', 'POST'])
def sslUpdatePage():
    if request.method == 'GET':
        try:
            session['username']
        except:
            return redirect('/')
        return render_template('multilingual/sslUpdatePage.html', userInfo=session['username'], auth=getAuth(session['username']), sslUpdateTime=(sslLastUpdate()[0])[:16])
    if request.method == 'POST':
        uploaded_file = request.files['sslUpdate']
        if uploaded_file.filename != " ":
            uploaded_file.save(os.path.join(
                app.config['UPLOAD_FOLDER'], uploaded_file.filename))
            print("SSL certificate uploaded!!")
            updateTime = datetime.datetime.now()
            print(updateTime)
            cursor.execute("Update conf set sslLastUpdate= ?", (updateTime,))
        con.commit()
        return redirect(url_for('multilingual.sslUpdatePage'))


sendDeviceParameters = 0


@multilingual.route('/userManagement', defaults={'lang_code': 'en'}, methods=['GET', 'POST'])
@multilingual.route('/kullaniciYonetimi', defaults={'lang_code': 'tr'}, methods=['GET', 'POST'])
def userManagement():
    if request.method == 'GET':
        try:
           session['username']
        except:
            return redirect('/')

app/templates/Div_ramUsage.html
<div class="input-box" id="ramUsageRefresh">
  <span class="details"> {{_('RAM Usage')}}</span>
  <input
    type="text"
    class="statusPageInputs inputsSameParameter"
    placeholder=""
    value="{%if ramUsage!=None%}{{ramUsage}}{%endif%}"
    disabled="true"
  />
</div>

app/templates/Div_statusversion.html
<div class="input-box" id="refreshVersion">
  <span class="details"> {{_('Firmware Version')}}</span>
  <div class="stage" id="loading">
    <div class="dot-pulse"></div>
  </div>
  <input
    type="text"
    class="statusPageInputs inputsSameParameter"
    placeholder=""
    value="{{firmware}}"
    disabled="true"
    id="Version"
  />
</div>
<script>
  var a = document.getElementById("Version").value;
  if (a == "None") {
    document.getElementById("Version").remove();
    document.getElementById("loading").style.visibility = "visible";
  } else {
    document.getElementById("Version").style.visibility = "visible";
    document.getElementById("loading").remove();
  }
</script>

app/templates/Div_systemTime.html
<div class="input-box" id="refreshTime">
  <span class="details"> {{_('System Time')}}</span>
  <input
    type="text"
    class="statusPageInputs inputsSameParameter"
    value="{%if time!=None%}{{time}}{%endif%}"
    disabled="true"
  />
</div>

app/templates/LeftSideBar.html
<link rel="stylesheet" href="/static/stylesheets/leftsidebar.css" />
<ul
  class="navbar-nav sidebar sidebar-dark accordion"
  id="accordionSidebar"
  style="
    background: rgb(24, 12, 52);
    background: linear-gradient(
      0deg,
      rgba(24, 12, 52, 0.7147233893557423) 0%,
      rgba(8, 116, 164, 1) 31%
    );
  "
>
  <!-- Sidebar - Brand -->
  <a
    class="sidebar-brand d-flex align-items-center justify-content-center"
    href="{{ url_for('multilingual.index') }}"
  >
    <div class="sidebar-brand-icon rotate-n-0">
      <br />
      <br />
      <img
        src="/static/images/sidebaricon.png"
        style="margin-top: 15px"
        width="200"
        height="38"
        id="sideBarIcon"
      />
      <img
        src="/static/icons/sidebaricon.png"
        width="40"
        height="38"
        id="sideBarIcon1"
      />
    </div>
  </a>
  <!-- Divider -->

  <hr class="sidebar-divider my-0" />

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="/">
      <img
        src="/static/icons/gauge-solid-removebg-preview.png"
        alt=""
        class="imageIcon"
        id="statusImage"
      />
      <span class="sidebarSpan" id="statusSpan">{{_('Status')}}</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />
  <!-- System -->
  {%if auth[0]=='Administrator' or auth[0]=='Technician' %}
  <div class="sidebar-heading">System</div>
  <li class="nav-item">
    {%if auth[0]=='Administrator'%}
    <a
      class="mynavlink"
      href="{{ url_for('multilingual.userManagement') }}"
      aria-expanded="true"
    >
      <img
        src="/static/icons/user-solid-removebg-preview.png"
        alt=""
        class="imageIcon"
      />
      <span class="sidebarSpan">{{_('User Management')}}</span>
    </a>
    {% endif %}
  </li>

  <li class="nav-item">
    <a
      class="mynavlink collapsed has-dropdown"
      href="#"
      data-toggle="collapse"
      data-target="#collapseUpload"
      aria-expanded="true"
      aria-controls="collapseUpload"
    >
      <img src="/static/icons/Removal-726.png" alt="" class="imageIcon" />
      <span class="sidebarSpan">{{_('Upload')}}</span>
      <img
        src="/static/icons/chevron-down-solid-removebg-preview.png"
        alt=""
        class="imageIcon alignArrow"
      />
    </a>
    <div
      id="collapseUpload"
      class="collapse"
      aria-labelledby="headingTwo"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">{{_('Update Device:')}}</h6>
        {%if auth[0]=='Administrator' or auth[0]=='Technician' %}
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.uploadProject') }}"
          title="Project Upload"
          >{{_('Project Upload')}}</a
        >
        {% endif %} {%if auth[0]=='Administrator' %}
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.uploadFirmware') }}"
          title="Firmware Upload"
          >{{_('Firmware Upload')}}</a
        >
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.sslUpdatePage') }}"
          >{{_('SSL Certificate Update')}}</a
        >
        {% endif %}
      </div>
    </div>
  </li>

  <!-- Heading -->
  <hr class="sidebar-divider" />

  <div class="sidebar-heading">{{_('Network')}}</div>

  {% endif %}

  <!-- Nav Item - Utilities Collapse Menu -->
  {%if auth[0]=='Administrator' or auth[0]=='Technician' %}
  <li class="nav-item">
    <a class="mynavlink" href="{{ url_for('multilingual.ipSettingsEth0') }}">
      <img src="/static/icons/Removal-815.png" alt="" class="imageIcon" />
      <span class="sidebarSpan">{{_('Interfaces')}}</span>
    </a>
  </li>
  {% endif %} {%if auth[0]=='Administrator' %}
  <li class="nav-item">
    <a
      class="mynavlink collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapseUtilities"
      aria-expanded="true"
      aria-controls="collapseUtilities"
    >
      <img src="/static/icons/firewall.png" alt="" class="imageIcon" />

      <span class="sidebarSpan">{{_('Firewall')}}</span>
      <img
        src="/static/icons/chevron-down-solid-removebg-preview.png"
        alt=""
        class="imageIcon alignArrow"
      />
    </a>
    <div
      id="collapseUtilities"
      class="collapse"
      aria-labelledby="headingUtilities"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">{{_('Firewall')}}</h6>
        <!--    <a class="collapse-item" href="utilities-border.html"
          >Device Settings</a
        > -->
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.filteringRules') }}"
          >{{_('Filtering Rules')}}</a
        >
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.portForwarding') }}"
          >{{_('Port Forwards')}}</a
        >
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.networkBridge') }}"
          >{{_('Network Bridge')}}</a
        >
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.natSettings') }}"
          >{{_('NAT')}}</a
        >
      </div>
    </div>
  </li>
  {% endif %} {%if auth[0]=='Administrator'%}
  <hr class="sidebar-divider" />
  <div class="sidebar-heading">{{_('Services')}}</div>

  <li class="nav-item">
    <a
      class="mynavlink collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#deviceLog"
      aria-expanded="true"
      aria-controls="deviceLog"
    >
      <img
        src="/static/icons/clock-rotate-left-solid-removebg-preview.png"
        alt=""
        class="imageIcon"
      />
      <span class="sidebarSpan">{{_('Device Log')}}</span>
      <img
        src="/static/icons/chevron-down-solid-removebg-preview.png"
        alt=""
        class="imageIcon alignArrow"
      />
    </a>
    <div
      id="deviceLog"
      class="collapse"
      aria-labelledby="headingUtilities"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">{{_('Device Log')}}</h6>
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.logview') }}"
          aria-expanded="true"
          >{{_('Logs')}}</a
        >
        <a
          class="collapse-item"
          href="{{ url_for('multilingual.syslog') }}"
          aria-expanded="true"
          >Remote Syslog</a
        >
      </div>
    </div>
  </li>
  {% endif %}

  <!-- Divider -->
  <hr class="sidebar-divider" />
  <!-- Heading -->
  <div class="sidebar-heading">{{_('Addons')}}</div>
  <!-- Nav Item - Pages Collapse Menu -->
  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a
      class="mynavlink collapsed"
      href="#"
      data-toggle="collapse"
      data-target="#collapseTables"
      aria-expanded="true"
      aria-controls="collapseTables"
    >
      <img
        src="/static/icons/table-cells-large-solid-removebg-preview.png"
        alt=""
        class="imageIcon"
      />
      <span class="sidebarSpan">{{_('Tables')}}</span>
      <img
        src="/static/icons/chevron-down-solid-removebg-preview.png"
        alt=""
        class="imageIcon alignArrow"
      />
    </a>
    <div
      id="collapseTables"
      class="collapse"
      aria-labelledby="headingPages"
      data-parent="#accordionSidebar"
    >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">{{_('Block Tables')}}</h6>
        <a class="collapse-item" href="{{ url_for('multilingual.webgui') }}"
          >{{_('Block Parameters')}}</a
        >
      </div>
    </div>
  </li>
</ul>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="selcuk" />
    <title>Mikrodev</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/stylesheets/font.css')}}"
    />
    <link
      href="{{ url_for('static', filename='/vendor/fontawesome-free/css/all.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/stylesheets/cards.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/stylesheets/leftsidebar.css')}}"
    />
    <link
      href="{{ url_for('static', filename='/stylesheets/sb-admin-2.min.css')}}"
      rel="stylesheet"
    />
  </head>
  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      {% include "LeftSideBar.html" %}

    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <nav
          class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          style="
            display: flex;
            align-items: center;
            justify-content: space-between;
          "
        >      
          <!-- Topbar Navbar -->
          <button
            id="sidebarToggle"
            class="btn btn-link d-block rounded-circle mr-3 midLogo"            
          >
            <img
              src="{{ url_for('static', filename='/icons/bars-solid.png')}}"
              alt=""
              style="height: 20px; width: 20px"
            />
          </button>
          <a href="/"
            ><img
              src="{{ url_for('static', filename='/images/mikrodev-logo-striped-removebg-preview.png')}}"
              class="midLogo"
              alt=""
              id="midImg"
          /></a>
          <div class="input-box alignmentEnd">
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <img src="/static/icons/turkey.png" id="icon" style="width: 30px; height:30px;"/>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="{{ url_for(request.endpoint, lang_code='tr') }}" class="dropdown-item" data-value="tr"><img src="/static/icons/turkey.png" id="icon" style="width: 30px; height:30px;"/>Türkçe</a></li>
                <li><a href="{{ url_for(request.endpoint, lang_code='en') }}" class="dropdown-item" data-value="en"><img src="/static/icons/united-kingdom.png" id="icon"style="width: 30px; height:30px;"/>English</a></li>
              </ul>
            </div>          
          </div>
          <div>{% include "userInfo.html" %}</div>          
        </nav>
        {% block content %}{% endblock %}
        <footer class="sticky-footer">
          <div class="my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Mikrodev 2022</span>
            </div>
          </div>
        </footer>
      </div>
      {% include "logoutModal.html" %}
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="timeOutWarningOverlay">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">{{_('Session Timeout')}}</h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>
              {{_('Your session is about to expire. Please click button below to
              keep this session current.')}}
            </p>
            <b
              ><span style="background-color: yellow">00:</span
              ><span id="time" style="background-color: yellow">59</span></b
            >
          </div>
          <div class="modal-footer">
            <button
              type="button"
              id="keep"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              {{_('Close')}}
            </button>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script src="{{url_for('static', filename='/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='/javascripts/sessionTimeOut.js')}}"></script>
  <script src="{{url_for('static', filename='/javascripts/sideBarToogle.js')}}"></script>
  <script src="{{url_for('static', filename='/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{url_for('static', filename='/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
  <script src="{{url_for('static', filename='/javascripts/ipvalidation.js')}}"></script>
  <script src="{{url_for('static', filename='/javascripts/laguageSelector.js')}}"></script>

</html>

app/templates/logoutModal.html
<div
  class="modal fade"
  id="logoutModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          {{_('Ready to Leave?')}}
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        {{_('Select "Logout" below if you are ready to end your current session.
        ')}}
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          {{_('Cancel')}}
        </button>
        <form
          action="{{url_for('multilingual.logout')}}"
          id="logout"
          method="post"
        >
          <a
            class="btn btn-primary"
            href="#"
            onclick="document.getElementById('logout').submit()"
          >
            {{_('Logout')}}
          </a>
        </form>
      </div>
    </div>
  </div>
</div>

app/templates/networkGsmStatus.html
<div class="containerBody" id="GSMrefresh">
  <span>{%if ATBAND != None %}IP:{{gsmIP}}{%endif%}</span>
  <span id="gsmBand">{%if ATBAND != None %}BAND:{{ATBAND}}{%endif%}</span>
  <span>{%if ATCSQ != None %}CSQ:{{ATCSQ}}{%endif%}</span>
  <script>
    var gsm = document.getElementById("gsmBand").innerHTML;
    if (
      gsm.includes("BAND:4") ||
      gsm.includes("BAND:3") ||
      gsm.includes("BAND:2")
    ) {
      try {
        document.getElementById("loading").remove();
      } catch {
        document.getElementById("gsmIntfContainer").style.borderColor = "green";
      }
    } else if (gsm.includes("BAND:-1")) {
      try {
        document.getElementById("loading").remove();
      } catch {
        document.getElementById("gsmIntfContainer").style.borderColor = "red";
      }
    } else {
      document.getElementById("gsmIntfContainer").style.borderColor = "gray";
      document.getElementById("loading").style.visibility = "visible";
    }
  </script>
</div>

app/templates/networkstatusETH0.html
<div class="containerBody" id="eth0Container">
  <span id="status">
    {%if dataType1 != None %}Status:{{netstatus[0]}}{%endif%}</span
  >
  <span>
    {%if dataType1 != None %}IP:{{dataType1[0]["LocalIp2"]}} {%endif%}</span
  >
  <span
    >{%if dataType1 != None %}NETMASK:/{{dataType1[0]["Netmask2"]}}
    {%endif%}</span
  >
  <span
    >{%if dataType1 != None %}GW:{{dataType1[0]["Gateway2"]}} {%endif%}</span
  >
  <script>
    var eth0Status = document.getElementById("status").innerHTML;
    if (eth0Status.includes("Status:UP")) {
      try {
        document.getElementById("loading").remove();
      } catch {}
      document.getElementById("eth0IntfContainer").style.borderColor = "green";
    } else if (eth0Status.includes("Status:DOWN")) {
      try {
        document.getElementById("loading").remove();
      } catch {}
      document.getElementById("eth0IntfContainer").style.borderColor = "red";
    } else {
      document.getElementById("eth0IntfContainer").style.borderColor = "gray";
      document.getElementById("loading").style.visibility = "visible";
      document.getElementById("eth0Container").remove();
    }
  </script>
</div>